name: Submission results

on:
  workflow_dispatch:
    inputs:
      batch:
        type: choice
        description: Batch
        options:
        - igt-icc
      assignment:
        type: choice
        description: Assignment name
        options:
        - spring
        - well-named
        - test-failer
        - simple-monitor
        - coverage
        - tdd-buckets
        - stream-line
      coverage:
        type: boolean
        description: Collect coverage

jobs:
  Welcome-all-submissions:
    name: Submissions of ${{ github.event.inputs.batch }} ${{ github.event.inputs.assignment }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run
      env:
        GITHUBAPI_TOKEN: ${{ secrets.GITHUBAPI_TOKEN }}
        GOOGLE_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
      run: |
        python list_repos.py --batch ${{ github.event.inputs.batch }} --interest ${{ github.event.inputs.assignment }} ${{ fromJSON('["", "--coverage"]')[github.event.inputs.coverage == 'true'] }}
