name: results

on:
  workflow_dispatch:
    inputs:
      org:
        type: choice
        description: Organization
        options:
        - tcq3
        - clean-s-1
        - tcq4
      assignment:
        type: choice
        description: Assignment name
        options:
        - well-named
        - test-failer
        - simple-monitor
        - coverage
        - tdd-buckets
        - stream-line
      title:
        type: choice
        description: Title suffix of Google Sheet
        options:
        - assignment
        - assessment
        - extension
      coverage:
        type: boolean
        description: Collect coverage

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "--org ${{ github.event.inputs.org }} --interest ${{ github.event.inputs.assignment }} --title ${{ github.event.inputs.org }}-${{ github.event.inputs.org }}-${{ github.event.inputs.title }} --coverage {{ github.inputs.coverage }}"
