name: results

on:
  workflow_dispatch:
    inputs:
      batch:
        type: choice
        description: Batch
        options:
        - tcq3
        - clean-s-1
        - tcq4
      assignment:
        type: choice
        description: Assignment name
        options:
        - well-named
        - test-failer
        - simple-monitor
        - coverage
        - tdd-buckets
        - stream-line
      coverage:
        type: boolean
        description: Collect coverage

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run
      run: |
        python list_repos.py --batch ${{ github.event.inputs.batch }} --interest ${{ github.event.inputs.assignment }} ${{ fromJSON('["", "--coverage"]')[github.event.inputs.coverage == 'true'] }}
